version: '2'
services:
  openvpn:
    container_name: openvpn
    image: wrongsides/openvpn
    ports:
      - "1194:1194/udp"
    volumes_from:
     - container: ovpn-data
    cap_add:
      - NET_ADMIN
  transmission:
    container_name: transmission
    image: wrongsides/transmission
    ports:
      - "9091:9091"
      - "54322:54322"
    volumes:
     - /mnt/share/config/transmission:/config
     - /mnt/share/transmission:/downloads
     - /etc/localtime:/etc/localtime:ro
  couchpotato:
    container_name: couchpotato
    image: wrongsides/couchpotato
    ports:
     - "5050:5050"
    volumes:
      - /mnt/share/config/couchpotato:/data
      - /mnt/share/:/share
  sickrage:
    container_name: sickrage
    image: wrongsides/sickrage
    ports:
      - "8081:8081"
    volumes:
     - /mnt/share/config/sickrage:/config
     - /mnt/share:/data
  plex:
    container_name: plex
    image: plexinc/pms-docker
    ports:
     - "32400:32400/tcp"
     - "3005:3005/tcp"
     - "8324:8324/tcp"
     - "32469:32469/tcp"
     - "1900:1900/udp"
     - "32410:32410/udp"
     - "32412:32412/udp"
     - "32413:32413/udp"
     - "32414:32414/udp"
    volumes:
     - "/mnt/share/config/plex:/config"
     - "/mnt/share/config/plex/temp:/transcode"
     - "/mnt/share:/mnt/share"
    environment:
     - TZ="Europe/London"
     - ADVERTISE_IP
     - PLEX_UID
     - PLEX_GID